export interface Document {
  id: string
  name: string
  acronym: string
  description: string
  purpose: string[]
  targetAudience: string[]
  requirements: string[]
  benefits: string[]
  deliveryTime: string
  validity: string
  category: 'Obrigatória' | 'Recomendada' | 'Especializada'
  price?: string
  includes: string[]
}

export const documentsData: Document[] = [
  {
    id: 'aep',
    name: 'Avaliação Ergonômica Preliminar',
    acronym: 'AEP',
    description: 'Documento técnico que identifica e avalia riscos ergonômicos no ambiente de trabalho',
    purpose: [
      'Identificar riscos ergonômicos no ambiente de trabalho',
      'Avaliar condições de trabalho e posturas inadequadas',
      'Prevenir doenças ocupacionais relacionadas ao trabalho',
      'Cumprir exigências da NR 17 (Ergonomia)',
    ],
    targetAudience: [
      'Empresas com mais de 20 funcionários',
      'Empresas com atividades que envolvem esforços físicos',
      'Empresas com trabalhos em posições estáticas',
      'Empresas com movimentação manual de cargas',
    ],
    requirements: [
      'Análise do ambiente de trabalho',
      'Avaliação das condições ergonômicas',
      'Identificação de riscos',
      'Propostas de melhorias',
    ],
    benefits: [
      'Prevenção de LER/DORT',
      'Melhoria da produtividade',
      'Redução de afastamentos',
      'Conformidade com NR 17',
      'Ambiente de trabalho mais saudável',
    ],
    deliveryTime: '5-7 dias úteis',
    validity: 'Indefinida (até mudanças no ambiente)',
    category: 'Obrigatória',
    includes: [
      'Análise ergonômica completa',
      'Relatório técnico detalhado',
      'Fotografias do ambiente',
      'Propostas de melhorias',
      'Laudo técnico assinado',
    ],
  },
  {
    id: 'aet',
    name: 'Análise Ergonômica do Trabalho',
    acronym: 'AET',
    description: 'Análise detalhada das condições ergonômicas e biomecânicas do trabalho',
    purpose: [
      'Analisar detalhadamente as condições ergonômicas',
      'Identificar fatores de risco biomecânicos',
      'Propor soluções ergonômicas específicas',
      'Atender exigências da NR 17',
    ],
    targetAudience: [
      'Empresas com problemas ergonômicos identificados',
      'Empresas com alto índice de LER/DORT',
      'Empresas que precisam de análise detalhada',
      'Empresas em processo de adequação ergonômica',
    ],
    requirements: [
      'Análise biomecânica detalhada',
      'Avaliação de posturas e movimentos',
      'Análise de equipamentos e mobiliário',
      'Estudo de cargas e esforços',
    ],
    benefits: [
      'Identificação precisa de riscos',
      'Soluções ergonômicas específicas',
      'Prevenção efetiva de doenças',
      'Melhoria da qualidade de vida',
      'Redução de custos com saúde',
    ],
    deliveryTime: '10-15 dias úteis',
    validity: 'Indefinida (até mudanças significativas)',
    category: 'Obrigatória',
    includes: [
      'Análise biomecânica completa',
      'Relatório técnico detalhado',
      'Fotografias e vídeos',
      'Propostas de melhorias específicas',
      'Laudo técnico assinado por especialista',
    ],
  },
  {
    id: 'apr',
    name: 'Análise Preliminar de Risco',
    acronym: 'APR',
    description: 'Identificação e avaliação preliminar de riscos em atividades e processos de trabalho',
    purpose: [
      'Identificar riscos potenciais nas atividades',
      'Avaliar a probabilidade e severidade dos riscos',
      'Estabelecer medidas de controle',
      'Prevenir acidentes e incidentes',
    ],
    targetAudience: [
      'Todas as empresas',
      'Empresas com atividades de risco',
      'Empresas que realizam trabalhos em altura',
      'Empresas com operações complexas',
    ],
    requirements: [
      'Identificação de perigos',
      'Avaliação de riscos',
      'Definição de medidas de controle',
      'Plano de ação',
    ],
    benefits: [
      'Prevenção de acidentes',
      'Identificação de perigos',
      'Melhoria da segurança',
      'Conformidade legal',
      'Redução de custos',
    ],
    deliveryTime: '3-5 dias úteis',
    validity: 'Anual ou quando houver mudanças',
    category: 'Obrigatória',
    includes: [
      'Análise de riscos completa',
      'Matriz de riscos',
      'Medidas de controle',
      'Plano de ação',
      'Relatório técnico',
    ],
  },
  {
    id: 'lip',
    name: 'Laudo de Insalubridade e Periculosidade',
    acronym: 'LIP',
    description: 'Laudo técnico que identifica e quantifica agentes insalubres e perigosos',
    purpose: [
      'Identificar agentes insalubres e perigosos',
      'Quantificar níveis de exposição',
      'Estabelecer medidas de controle',
      'Definir pagamentos de adicionais',
    ],
    targetAudience: [
      'Empresas com agentes insalubres',
      'Empresas com atividades perigosas',
      'Empresas que precisam de laudo técnico',
      'Empresas em processo de adequação',
    ],
    requirements: [
      'Avaliação ambiental',
      'Medições técnicas',
      'Análise de agentes físicos, químicos e biológicos',
      'Relatório técnico detalhado',
    ],
    benefits: [
      'Conformidade legal',
      'Definição correta de adicionais',
      'Proteção dos trabalhadores',
      'Prevenção de doenças',
      'Redução de passivos trabalhistas',
    ],
    deliveryTime: '7-10 dias úteis',
    validity: 'Anual ou quando houver mudanças',
    category: 'Obrigatória',
    includes: [
      'Avaliação ambiental completa',
      'Medições técnicas',
      'Relatório técnico detalhado',
      'Laudo técnico assinado',
      'Recomendações técnicas',
    ],
  },
  {
    id: 'ltcat',
    name: 'Laudo Técnico das Condições do Ambiente de Trabalho',
    acronym: 'LTCAT',
    description: 'Laudo técnico que avalia as condições do ambiente de trabalho para fins previdenciários',
    purpose: [
      'Avaliar condições do ambiente de trabalho',
      'Identificar agentes nocivos',
      'Estabelecer medidas de controle',
      'Atender exigências previdenciárias',
    ],
    targetAudience: [
      'Todas as empresas',
      'Empresas com agentes nocivos',
      'Empresas que precisam de laudo técnico',
      'Empresas em processo de adequação',
    ],
    requirements: [
      'Avaliação do ambiente de trabalho',
      'Identificação de agentes nocivos',
      'Medições técnicas quando necessário',
      'Relatório técnico detalhado',
    ],
    benefits: [
      'Conformidade previdenciária',
      'Identificação de riscos',
      'Prevenção de doenças',
      'Proteção dos trabalhadores',
      'Redução de passivos',
    ],
    deliveryTime: '5-7 dias úteis',
    validity: 'Anual ou quando houver mudanças',
    category: 'Obrigatória',
    includes: [
      'Avaliação ambiental completa',
      'Relatório técnico detalhado',
      'Laudo técnico assinado',
      'Recomendações técnicas',
      'Documentação fotográfica',
    ],
  },
  {
    id: 'os',
    name: 'Ordem de Serviço',
    acronym: 'OS',
    description: 'Documento que estabelece procedimentos de segurança para atividades específicas',
    purpose: [
      'Estabelecer procedimentos de segurança',
      'Identificar riscos específicos',
      'Definir medidas de proteção',
      'Treinar trabalhadores',
    ],
    targetAudience: [
      'Todas as empresas',
      'Empresas com atividades de risco',
      'Empresas que precisam de procedimentos',
      'Empresas em processo de adequação',
    ],
    requirements: [
      'Identificação de riscos',
      'Procedimentos de segurança',
      'Medidas de proteção',
      'Treinamento dos trabalhadores',
    ],
    benefits: [
      'Padronização de procedimentos',
      'Prevenção de acidentes',
      'Treinamento dos trabalhadores',
      'Conformidade legal',
      'Melhoria da segurança',
    ],
    deliveryTime: '3-5 dias úteis',
    validity: 'Até mudanças nos procedimentos',
    category: 'Obrigatória',
    includes: [
      'Procedimentos de segurança',
      'Identificação de riscos',
      'Medidas de proteção',
      'Treinamento dos trabalhadores',
      'Documento assinado',
    ],
  },
  {
    id: 'pca',
    name: 'Programa de Conservação Auditiva',
    acronym: 'PCA',
    description: 'Programa que previne e controla a perda auditiva ocupacional',
    purpose: [
      'Prevenir perda auditiva ocupacional',
      'Controlar exposição ao ruído',
      'Monitorar a saúde auditiva',
      'Atender exigências da NR 7',
    ],
    targetAudience: [
      'Empresas com exposição ao ruído',
      'Empresas com atividades ruidosas',
      'Empresas que precisam de PCA',
      'Empresas em processo de adequação',
    ],
    requirements: ['Avaliação do ruído', 'Medições técnicas', 'Programa de controle', 'Monitoramento da saúde'],
    benefits: [
      'Prevenção de perda auditiva',
      'Conformidade com NR 7',
      'Proteção dos trabalhadores',
      'Redução de passivos',
      'Melhoria da qualidade de vida',
    ],
    deliveryTime: '10-15 dias úteis',
    validity: 'Anual ou quando houver mudanças',
    category: 'Obrigatória',
    includes: [
      'Avaliação do ruído',
      'Programa de controle',
      'Medidas de proteção',
      'Treinamento dos trabalhadores',
      'Documentação completa',
    ],
  },
  {
    id: 'pcmso',
    name: 'Programa de Controle Médico de Saúde Ocupacional',
    acronym: 'PCMSO',
    description: 'Programa que monitora e controla a saúde dos trabalhadores',
    purpose: [
      'Monitorar a saúde dos trabalhadores',
      'Prevenir doenças ocupacionais',
      'Controlar exposição a agentes nocivos',
      'Atender exigências da NR 7',
    ],
    targetAudience: [
      'Todas as empresas',
      'Empresas com agentes nocivos',
      'Empresas que precisam de PCMSO',
      'Empresas em processo de adequação',
    ],
    requirements: ['Exames médicos', 'Monitoramento da saúde', 'Controle de agentes nocivos', 'Programa de prevenção'],
    benefits: [
      'Prevenção de doenças',
      'Conformidade com NR 7',
      'Proteção dos trabalhadores',
      'Redução de passivos',
      'Melhoria da qualidade de vida',
    ],
    deliveryTime: '15-20 dias úteis',
    validity: 'Anual',
    category: 'Obrigatória',
    includes: [
      'Programa completo de saúde',
      'Exames médicos',
      'Monitoramento da saúde',
      'Relatórios médicos',
      'Documentação completa',
    ],
  },
  {
    id: 'pet',
    name: 'Permissão de Entrada e Trabalho',
    acronym: 'PET',
    description: 'Documento que autoriza e controla trabalhos em espaços confinados',
    purpose: [
      'Autorizar trabalhos em espaços confinados',
      'Controlar entrada e saída',
      'Estabelecer procedimentos de segurança',
      'Atender exigências da NR 33',
    ],
    targetAudience: [
      'Empresas com espaços confinados',
      'Empresas que realizam trabalhos confinados',
      'Empresas que precisam de PET',
      'Empresas em processo de adequação',
    ],
    requirements: [
      'Identificação de riscos',
      'Procedimentos de segurança',
      'Equipamentos de proteção',
      'Treinamento dos trabalhadores',
    ],
    benefits: [
      'Controle de trabalhos confinados',
      'Prevenção de acidentes',
      'Conformidade com NR 33',
      'Proteção dos trabalhadores',
      'Melhoria da segurança',
    ],
    deliveryTime: '3-5 dias úteis',
    validity: 'Por trabalho ou período definido',
    category: 'Obrigatória',
    includes: [
      'Permissão de entrada',
      'Procedimentos de segurança',
      'Identificação de riscos',
      'Medidas de proteção',
      'Documento assinado',
    ],
  },
  {
    id: 'pgr',
    name: 'Programa de Gerenciamento de Riscos',
    acronym: 'PGR',
    description: 'Programa que gerencia riscos de forma sistemática e contínua',
    purpose: [
      'Gerenciar riscos de forma sistemática',
      'Identificar e avaliar riscos',
      'Estabelecer controles',
      'Monitorar e revisar riscos',
    ],
    targetAudience: [
      'Empresas de médio e grande porte',
      'Empresas com múltiplos riscos',
      'Empresas que precisam de PGR',
      'Empresas em processo de adequação',
    ],
    requirements: ['Identificação de riscos', 'Avaliação de riscos', 'Controles de riscos', 'Monitoramento e revisão'],
    benefits: [
      'Gerenciamento sistemático de riscos',
      'Prevenção de acidentes',
      'Conformidade legal',
      'Redução de custos',
      'Melhoria da segurança',
    ],
    deliveryTime: '2-3 dias úteis',
    validity: 'Anual ou quando houver mudanças',
    category: 'Recomendada',
    includes: [
      'Programa completo de gerenciamento',
      'Identificação de riscos',
      'Controles de riscos',
      'Monitoramento e revisão',
      'Documentação completa',
    ],
  },
  {
    id: 'ppr',
    name: 'Programa de Proteção Respiratória',
    acronym: 'PPR',
    description: 'Programa que controla a exposição a agentes respiratórios',
    purpose: [
      'Controlar exposição a agentes respiratórios',
      'Selecionar equipamentos de proteção',
      'Treinar trabalhadores',
      'Monitorar a saúde',
    ],
    targetAudience: [
      'Empresas com agentes respiratórios',
      'Empresas com poeiras, vapores ou gases',
      'Empresas que precisam de PPR',
      'Empresas em processo de adequação',
    ],
    requirements: [
      'Avaliação de agentes respiratórios',
      'Seleção de equipamentos',
      'Treinamento dos trabalhadores',
      'Monitoramento da saúde',
    ],
    benefits: [
      'Controle de exposição',
      'Prevenção de doenças',
      'Conformidade legal',
      'Proteção dos trabalhadores',
      'Melhoria da qualidade de vida',
    ],
    deliveryTime: '10-15 dias úteis',
    validity: 'Anual ou quando houver mudanças',
    category: 'Obrigatória',
    includes: [
      'Programa de proteção respiratória',
      'Seleção de equipamentos',
      'Treinamento dos trabalhadores',
      'Monitoramento da saúde',
      'Documentação completa',
    ],
  },
  {
    id: 'ppp',
    name: 'Perfil Profissiográfico Previdenciário',
    acronym: 'PPP',
    description: 'Documento que registra a exposição a agentes nocivos durante a vida laboral',
    purpose: [
      'Registrar exposição a agentes nocivos',
      'Documentar condições de trabalho',
      'Auxiliar em processos previdenciários',
      'Atender exigências previdenciárias',
    ],
    targetAudience: [
      'Todas as empresas',
      'Empresas com agentes nocivos',
      'Empresas que precisam de PPP',
      'Empresas em processo de adequação',
    ],
    requirements: [
      'Registro de exposição',
      'Documentação de condições',
      'Avaliação de agentes nocivos',
      'Relatório técnico',
    ],
    benefits: [
      'Registro de exposição',
      'Documentação de condições',
      'Auxílio em processos previdenciários',
      'Conformidade legal',
      'Proteção dos trabalhadores',
    ],
    deliveryTime: '5-7 dias úteis',
    validity: 'Atualização contínua',
    category: 'Obrigatória',
    includes: [
      'Registro de exposição',
      'Documentação de condições',
      'Relatório técnico',
      'Laudo técnico assinado',
      'Documentação completa',
    ],
  },
]

export const documentCategories = [
  { id: 'all', name: 'Todas as Documentações', count: documentsData.length },
  {
    id: 'Obrigatória',
    name: 'Documentações Obrigatórias',
    count: documentsData.filter((d) => d.category === 'Obrigatória').length,
  },
  {
    id: 'Recomendada',
    name: 'Documentações Recomendadas',
    count: documentsData.filter((d) => d.category === 'Recomendada').length,
  },
  {
    id: 'Especializada',
    name: 'Documentações Especializadas',
    count: documentsData.filter((d) => d.category === 'Especializada').length,
  },
]
