export interface Training {
  id: string
  name: string
  hours: string
  description: string
  objectives: string[]
  targetAudience: string[]
  content: string[]
  benefits: string[]
  requirements?: string[]
  certification: string
  price?: string
  category: 'NR' | 'Especializado' | 'Básico'
}

export const trainingsData: Training[] = [
  {
    id: 'cipamin',
    name: 'CIPAMIN',
    hours: '40h',
    description: 'Curso de Capacitação para Instrutores de Prevenção de Acidentes do Trabalho em Mineração',
    objectives: [
      'Formar instrutores qualificados para ministrar treinamentos de segurança em mineração',
      'Capacitar profissionais para atuar na prevenção de acidentes do trabalho',
      'Transmitir conhecimentos sobre legislação e normas de segurança aplicáveis',
    ],
    targetAudience: [
      'Profissionais de segurança do trabalho',
      'Engenheiros de minas',
      'Técnicos de segurança',
      'Supervisores de mineração',
    ],
    content: [
      'Legislação de segurança do trabalho',
      'Normas regulamentadoras aplicáveis',
      'Prevenção de acidentes em mineração',
      'Metodologia de ensino',
      'Didática aplicada à segurança',
    ],
    benefits: [
      'Certificação reconhecida pelo MTE',
      'Qualificação para ministrar treinamentos',
      'Conhecimento aprofundado em segurança',
      'Melhoria na carreira profissional',
    ],
    certification: 'Certificado válido em todo território nacional',
    category: 'Especializado',
  },
  {
    id: 'primeiros-socorros',
    name: 'Noções de Primeiros Socorros',
    hours: '2h',
    description: 'Treinamento essencial para capacitar colaboradores em procedimentos básicos de primeiros socorros',
    objectives: [
      'Capacitar colaboradores para identificar emergências médicas',
      'Ensinar procedimentos básicos de primeiros socorros',
      'Preparar equipes para situações de emergência',
    ],
    targetAudience: ['Todos os colaboradores da empresa', 'Brigadistas', 'Equipes de segurança'],
    content: [
      'Identificação de emergências médicas',
      'Procedimentos básicos de primeiros socorros',
      'Suporte básico de vida',
      'Prevenção de acidentes',
    ],
    benefits: [
      'Maior segurança no ambiente de trabalho',
      'Redução de consequências de acidentes',
      'Conformidade com legislação',
      'Preparação para emergências',
    ],
    certification: 'Certificado de participação',
    category: 'Básico',
  },
  {
    id: 'nr05-cipa-gr1',
    name: 'NR 05 – CIPA [Grau de Risco 1]',
    hours: '8h',
    description: 'Formação de membros da Comissão Interna de Prevenção de Acidentes para empresas de grau de risco 1',
    objectives: [
      'Formar membros da CIPA conforme NR 05',
      'Capacitar para identificação de riscos',
      'Preparar para elaboração do mapa de riscos',
    ],
    targetAudience: ['Membros eleitos da CIPA', 'Suplentes da CIPA', 'Profissionais indicados pela empresa'],
    content: [
      'Organização da CIPA',
      'Atribuições da CIPA',
      'Riscos ambientais',
      'Mapa de riscos',
      'Prevenção de acidentes',
    ],
    benefits: [
      'Conformidade com NR 05',
      'Redução de acidentes de trabalho',
      'Melhoria na segurança',
      'Participação ativa na segurança',
    ],
    certification: 'Certificado válido conforme NR 05',
    category: 'NR',
  },
  {
    id: 'nr05-cipa-gr2',
    name: 'NR 05 – CIPA [Grau de Risco 2]',
    hours: '8h',
    description: 'Formação de membros da Comissão Interna de Prevenção de Acidentes para empresas de grau de risco 2',
    objectives: [
      'Formar membros da CIPA conforme NR 05',
      'Capacitar para identificação de riscos específicos',
      'Preparar para elaboração do mapa de riscos',
    ],
    targetAudience: ['Membros eleitos da CIPA', 'Suplentes da CIPA', 'Profissionais indicados pela empresa'],
    content: [
      'Organização da CIPA',
      'Atribuições da CIPA',
      'Riscos ambientais específicos',
      'Mapa de riscos',
      'Prevenção de acidentes',
    ],
    benefits: [
      'Conformidade com NR 05',
      'Redução de acidentes de trabalho',
      'Melhoria na segurança',
      'Participação ativa na segurança',
    ],
    certification: 'Certificado válido conforme NR 05',
    category: 'NR',
  },
  {
    id: 'nr06-epi',
    name: 'NR 06 – Equipamentos de Proteção Individual',
    hours: '4h',
    description: 'Treinamento sobre seleção, uso e conservação de Equipamentos de Proteção Individual',
    objectives: [
      'Capacitar para seleção adequada de EPIs',
      'Ensinar uso correto dos equipamentos',
      'Orientar sobre conservação e manutenção',
    ],
    targetAudience: ['Usuários de EPIs', 'Profissionais de segurança', 'Supervisores de produção'],
    content: ['Tipos de EPIs', 'Seleção adequada', 'Uso correto', 'Conservação e manutenção', 'Responsabilidades'],
    benefits: ['Uso correto de EPIs', 'Maior proteção individual', 'Redução de acidentes', 'Conformidade com NR 06'],
    certification: 'Certificado de participação',
    category: 'NR',
  },
  {
    id: 'nr10-basico',
    name: 'NR 10 – Segurança em Instalações Elétricas',
    hours: '40h',
    description: 'Curso básico de segurança em instalações e serviços com eletricidade',
    objectives: [
      'Capacitar para trabalhos com eletricidade',
      'Prevenir acidentes elétricos',
      'Conhecer procedimentos de segurança',
    ],
    targetAudience: ['Eletricistas', 'Técnicos de manutenção', 'Profissionais que trabalham com eletricidade'],
    content: [
      'Riscos elétricos',
      'Medidas de controle',
      'Equipamentos de proteção',
      'Procedimentos de segurança',
      'Primeiros socorros',
    ],
    benefits: [
      'Qualificação para trabalhos elétricos',
      'Prevenção de acidentes',
      'Conformidade com NR 10',
      'Maior segurança no trabalho',
    ],
    certification: 'Certificado válido conforme NR 10',
    category: 'NR',
  },
  {
    id: 'nr10-reciclagem',
    name: 'NR 10 – Reciclagem Bienal',
    hours: '16h',
    description: 'Reciclagem obrigatória para profissionais que trabalham com eletricidade',
    objectives: [
      'Atualizar conhecimentos em segurança elétrica',
      'Revisar procedimentos de segurança',
      'Manter qualificação profissional',
    ],
    targetAudience: [
      'Profissionais com curso NR 10 básico',
      'Eletricistas em atividade',
      'Técnicos de manutenção elétrica',
    ],
    content: ['Atualizações normativas', 'Novos procedimentos de segurança', 'Revisão de conceitos', 'Casos práticos'],
    benefits: [
      'Manutenção da qualificação',
      'Atualização de conhecimentos',
      'Conformidade com NR 10',
      'Reciclagem profissional',
    ],
    certification: 'Certificado de reciclagem NR 10',
    category: 'NR',
  },
  {
    id: 'nr11-transporte',
    name: 'NR 11 – Transporte e Movimentação',
    hours: '6h',
    description: 'Treinamento sobre segurança na movimentação, armazenagem e manuseio de materiais',
    objectives: [
      'Capacitar para movimentação segura de cargas',
      'Prevenir acidentes na movimentação',
      'Conhecer equipamentos de movimentação',
    ],
    targetAudience: ['Operadores de empilhadeiras', 'Profissionais de logística', 'Operadores de guindastes'],
    content: ['Equipamentos de movimentação', 'Procedimentos de segurança', 'Sinalizações', 'Prevenção de acidentes'],
    benefits: [
      'Operação segura de equipamentos',
      'Redução de acidentes',
      'Conformidade com NR 11',
      'Maior eficiência operacional',
    ],
    certification: 'Certificado de participação',
    category: 'NR',
  },
  {
    id: 'nr12-maquinas',
    name: 'NR 12 – Segurança em Máquinas',
    hours: '4h',
    description: 'Treinamento sobre segurança na operação e manutenção de máquinas e equipamentos',
    objectives: [
      'Capacitar para operação segura de máquinas',
      'Prevenir acidentes com máquinas',
      'Conhecer dispositivos de segurança',
    ],
    targetAudience: ['Operadores de máquinas', 'Técnicos de manutenção', 'Supervisores de produção'],
    content: [
      'Dispositivos de segurança',
      'Procedimentos de operação',
      'Manutenção preventiva',
      'Prevenção de acidentes',
    ],
    benefits: ['Operação segura de máquinas', 'Redução de acidentes', 'Conformidade com NR 12', 'Maior produtividade'],
    certification: 'Certificado de participação',
    category: 'NR',
  },
  {
    id: 'nr20-basico',
    name: 'NR 20 – Curso Básico',
    hours: '4h',
    description: 'Treinamento básico sobre segurança e saúde no trabalho com inflamáveis e combustíveis',
    objectives: [
      'Capacitar para trabalhos com inflamáveis',
      'Prevenir acidentes com combustíveis',
      'Conhecer procedimentos de segurança',
    ],
    targetAudience: [
      'Profissionais que trabalham com inflamáveis',
      'Operadores de postos de combustível',
      'Técnicos de manutenção',
    ],
    content: [
      'Propriedades dos inflamáveis',
      'Riscos e perigos',
      'Procedimentos de segurança',
      'Prevenção de acidentes',
    ],
    benefits: [
      'Trabalho seguro com inflamáveis',
      'Prevenção de acidentes',
      'Conformidade com NR 20',
      'Maior segurança no trabalho',
    ],
    certification: 'Certificado válido conforme NR 20',
    category: 'NR',
  },
  {
    id: 'nr23-incendio',
    name: 'NR 23 – Prevenção e Combate a Incêndio',
    hours: '8h',
    description: 'Treinamento sobre prevenção e combate a incêndios em estabelecimentos',
    objectives: [
      'Capacitar para prevenção de incêndios',
      'Ensinar técnicas de combate a incêndio',
      'Preparar brigadas de incêndio',
    ],
    targetAudience: ['Brigadistas de incêndio', 'Profissionais de segurança', 'Colaboradores em geral'],
    content: ['Teoria do fogo', 'Classes de incêndio', 'Prevenção de incêndios', 'Combate a incêndios', 'Evacuação'],
    benefits: ['Prevenção de incêndios', 'Capacitação para emergências', 'Conformidade com NR 23', 'Maior segurança'],
    certification: 'Certificado válido conforme NR 23',
    category: 'NR',
  },
  {
    id: 'nr33-espacos-confinados',
    name: 'NR 33 – Espaços Confinados',
    hours: '16h',
    description: 'Treinamento para trabalho em espaços confinados conforme NR 33',
    objectives: [
      'Capacitar para trabalhos em espaços confinados',
      'Prevenir acidentes em ambientes confinados',
      'Conhecer procedimentos de segurança',
    ],
    targetAudience: ['Profissionais que trabalham em espaços confinados', 'Supervisores de entrada', 'Vigias'],
    content: [
      'Definição de espaços confinados',
      'Riscos e perigos',
      'Medidas de controle',
      'Procedimentos de entrada',
      'Equipamentos de proteção',
    ],
    benefits: [
      'Trabalho seguro em espaços confinados',
      'Prevenção de acidentes',
      'Conformidade com NR 33',
      'Maior segurança no trabalho',
    ],
    certification: 'Certificado válido conforme NR 33',
    category: 'NR',
  },
  {
    id: 'nr35-altura',
    name: 'NR 35 – Trabalho em Altura',
    hours: '8h',
    description: 'Treinamento para trabalho em altura conforme NR 35',
    objectives: [
      'Capacitar para trabalhos em altura',
      'Prevenir acidentes em trabalhos elevados',
      'Conhecer equipamentos de proteção',
    ],
    targetAudience: ['Profissionais que trabalham em altura', 'Operadores de andaimes', 'Técnicos de manutenção'],
    content: [
      'Riscos do trabalho em altura',
      'Equipamentos de proteção',
      'Procedimentos de segurança',
      'Prevenção de quedas',
    ],
    benefits: [
      'Trabalho seguro em altura',
      'Prevenção de acidentes',
      'Conformidade com NR 35',
      'Maior segurança no trabalho',
    ],
    certification: 'Certificado válido conforme NR 35',
    category: 'NR',
  },
  {
    id: 'nr38-limpeza-urbana',
    name: 'NR 38 – Limpeza Urbana',
    hours: '7h',
    description: 'Treinamento sobre segurança e saúde no trabalho em limpeza urbana',
    objectives: [
      'Capacitar para trabalhos de limpeza urbana',
      'Prevenir acidentes na limpeza urbana',
      'Conhecer procedimentos de segurança',
    ],
    targetAudience: ['Profissionais de limpeza urbana', 'Coletores de lixo', 'Varredores de rua'],
    content: [
      'Riscos da limpeza urbana',
      'Equipamentos de proteção',
      'Procedimentos de segurança',
      'Prevenção de acidentes',
    ],
    benefits: [
      'Trabalho seguro na limpeza urbana',
      'Redução de acidentes',
      'Conformidade com NR 38',
      'Maior segurança no trabalho',
    ],
    certification: 'Certificado válido conforme NR 38',
    category: 'NR',
  },
]

export const trainingCategories = [
  { id: 'all', name: 'Todos os Treinamentos', count: trainingsData.length },
  { id: 'NR', name: 'Normas Regulamentadoras', count: trainingsData.filter((t) => t.category === 'NR').length },
  {
    id: 'Especializado',
    name: 'Cursos Especializados',
    count: trainingsData.filter((t) => t.category === 'Especializado').length,
  },
  { id: 'Básico', name: 'Treinamentos Básicos', count: trainingsData.filter((t) => t.category === 'Básico').length },
]
